// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0
// source: tour.proto

package tour

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Tour_Create_FullMethodName      = "/Tour/Create"
	Tour_GetByUserId_FullMethodName = "/Tour/GetByUserId"
	Tour_Publish_FullMethodName     = "/Tour/Publish"
	Tour_Archive_FullMethodName     = "/Tour/Archive"
	Tour_Delete_FullMethodName      = "/Tour/Delete"
)

// TourClient is the client API for Tour service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourClient interface {
	Create(ctx context.Context, in *TourDto, opts ...grpc.CallOption) (*TourDto, error)
	GetByUserId(ctx context.Context, in *PageRequestTour, opts ...grpc.CallOption) (*TourListResponse, error)
	Publish(ctx context.Context, in *TourPublishRequest, opts ...grpc.CallOption) (*TourDto, error)
	Archive(ctx context.Context, in *TourPublishRequest, opts ...grpc.CallOption) (*TourDto, error)
	Delete(ctx context.Context, in *TourIdRequest, opts ...grpc.CallOption) (*TourDto, error)
}

type tourClient struct {
	cc grpc.ClientConnInterface
}

func NewTourClient(cc grpc.ClientConnInterface) TourClient {
	return &tourClient{cc}
}

func (c *tourClient) Create(ctx context.Context, in *TourDto, opts ...grpc.CallOption) (*TourDto, error) {
	out := new(TourDto)
	err := c.cc.Invoke(ctx, Tour_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) GetByUserId(ctx context.Context, in *PageRequestTour, opts ...grpc.CallOption) (*TourListResponse, error) {
	out := new(TourListResponse)
	err := c.cc.Invoke(ctx, Tour_GetByUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) Publish(ctx context.Context, in *TourPublishRequest, opts ...grpc.CallOption) (*TourDto, error) {
	out := new(TourDto)
	err := c.cc.Invoke(ctx, Tour_Publish_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) Archive(ctx context.Context, in *TourPublishRequest, opts ...grpc.CallOption) (*TourDto, error) {
	out := new(TourDto)
	err := c.cc.Invoke(ctx, Tour_Archive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourClient) Delete(ctx context.Context, in *TourIdRequest, opts ...grpc.CallOption) (*TourDto, error) {
	out := new(TourDto)
	err := c.cc.Invoke(ctx, Tour_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServer is the server API for Tour service.
// All implementations must embed UnimplementedTourServer
// for forward compatibility
type TourServer interface {
	Create(context.Context, *TourDto) (*TourDto, error)
	GetByUserId(context.Context, *PageRequestTour) (*TourListResponse, error)
	Publish(context.Context, *TourPublishRequest) (*TourDto, error)
	Archive(context.Context, *TourPublishRequest) (*TourDto, error)
	Delete(context.Context, *TourIdRequest) (*TourDto, error)
	mustEmbedUnimplementedTourServer()
}

// UnimplementedTourServer must be embedded to have forward compatible implementations.
type UnimplementedTourServer struct {
}

func (UnimplementedTourServer) Create(context.Context, *TourDto) (*TourDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTourServer) GetByUserId(context.Context, *PageRequestTour) (*TourListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUserId not implemented")
}
func (UnimplementedTourServer) Publish(context.Context, *TourPublishRequest) (*TourDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedTourServer) Archive(context.Context, *TourPublishRequest) (*TourDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Archive not implemented")
}
func (UnimplementedTourServer) Delete(context.Context, *TourIdRequest) (*TourDto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTourServer) mustEmbedUnimplementedTourServer() {}

// UnsafeTourServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServer will
// result in compilation errors.
type UnsafeTourServer interface {
	mustEmbedUnimplementedTourServer()
}

func RegisterTourServer(s grpc.ServiceRegistrar, srv TourServer) {
	s.RegisterService(&Tour_ServiceDesc, srv)
}

func _Tour_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).Create(ctx, req.(*TourDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_GetByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequestTour)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).GetByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_GetByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).GetByUserId(ctx, req.(*PageRequestTour))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourPublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).Publish(ctx, req.(*TourPublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_Archive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourPublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).Archive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_Archive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).Archive(ctx, req.(*TourPublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tour_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tour_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServer).Delete(ctx, req.(*TourIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tour_ServiceDesc is the grpc.ServiceDesc for Tour service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tour_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Tour",
	HandlerType: (*TourServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Tour_Create_Handler,
		},
		{
			MethodName: "GetByUserId",
			Handler:    _Tour_GetByUserId_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _Tour_Publish_Handler,
		},
		{
			MethodName: "Archive",
			Handler:    _Tour_Archive_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Tour_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tour.proto",
}
